@ECHO off
ECHO decoding apk with apktool...
java -jar lib/apktool.jar d -f -r -s -o "%TEMP%\apk2java\%1" "%1" >> nul
ECHO converting classes.dex to jar with dex2jar...
java -Xms512m -Xmx1024m -cp "lib/asm-debug-all-4.1.jar;lib/d2j-base-cmd-2.0.jar;lib/dex-ir-2.0.jar;lib/dex-reader-2.0.jar;lib/dex-reader-api-2.0.jar;lib/dex-tools-2.0.jar;lib/dex-translator-2.0.jar" com.googlecode.dex2jar.tools.Dex2jarCmd -f -o "%1.jar" "%TEMP%\apk2java\%1\classes.dex" >> nul
ECHO deleting temp files...
RD /S /Q "%TEMP%\apk2java\%1"
ECHO opening the jar with jd-gui...
start jd-gui.jar "%1.jar"